### ISSUE TITLE
cluster 0.13.0 or 0.13.1 - influxdb: check "http" is missing

### ISSUE THREAD

**Issue by Openpony** [liquidinvestigations/cluster#131] opened 2021-04-14 12:22 UTC
Trying to deploy cluster in version 0.13.1 but impossible, still have this error : 

2021-04-14 11:50:17 cluster.py wait_for_consul()     INFO Consul UP and running with leader 10.66.60.1:8300
2021-04-14 11:50:47 cluster.py wait_for_checks()     INFO Checks for ['nomad', 'nomad-client', 'vault'] green after 29.57s
2021-04-14 11:51:01 cluster.py wait_for_checks()     INFO Checks for ['cluster-fabio', 'telegraf'] green after 14.04s
2021-04-14 11:56:35 cluster.py     <module>()    ERROR Checks are failing after 334.27s: 
 
 - influxdb: check "http" is missing
Traceback (most recent call last):
  File "./cluster.py", line 866, in <module>
    cli()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./cluster.py", line 747, in wait
    k: v for k, v in HEALTH_CHECKS.items()
  File "./cluster.py", line 677, in wait_for_checks
    raise RuntimeError(msg)
RuntimeError: Checks are failing after 334.27s: 

 - influxdb: check "http" is missing

**Comment by gabriel-v** [comment] 2021-04-14 12:27
closing as duplicate of #125

**Closed by gabriel-v** 2021-04-14 12:27 UTC
